### ISSUE TITLE
Running Desktop

### ISSUE THREAD

**Issue by burf2000** [Pishka/gdx-Gnoblin#1]
I get the following error?

Exception in thread "LWJGL Application" java.lang.NullPointerException
    at com.badlogic.gdx.scenes.scene2d.ui.Skin.add(Skin.java:111)
    at ru.alastar.gui.GUICore.CreateDefaultSkin(GUICore.java:42)
    at ru.alastar.Engine.init(Engine.java:372)
    at ru.alastar.MainScreen.<init>(MainScreen.java:49)
    at ru.alastar.Main.create(Main.java:17)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by ghost** [comment]
Most possible reason - engine can't find its default font. Font is located at res/data/fonts called tahoma.ttf. There must be debug message in the console: "Standart font is null!". You can fix this error by copying font to the specified dir, or change directory with setFontFilesDir(path) method, path is local - relative to the programm dir. Sorry for long response, I visit github very rarely.
